project_id = "zevlrzothrwmemspmgtz"

[functions.create-test-employee]
verify_jwt = true

[functions.create-hr-user]
verify_jwt = true

[functions.generate-development-recommendations]
verify_jwt = true